version: '3'
services:
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
    command: ["python", "-u", "./server.py"]

  agent:
    container_name: agent
    build: ./agent
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080
