version: '3'
services:
  server:
    container_name: server
    build: ./server
    ports:
      - "5000:5000"

  agent:
    container_name: agent
    build: ./agent
    extra_hosts:
    - "server:127.0.0.10"
    depends_on:
      - server
    command: ["python", "-u", "./agent.py"]
